name: fair
description: Flutter Fair is a package used to update widget dynamically.
version: 2.0.0
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  fair_annotation: ^0.2.0
  fair_annotation:
    path: ../annotation

#  fair_version: ^0.2.0
  fair_version:
    path: ../flutter_version/flutter_2_0_6

  flat_buffers: ^2.0.5
  url_launcher: ^6.0.10
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^2.1.0
  pedantic: ^1.11.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.wuba.fair
    pluginClass: FairPlugin
  assets:
    - assets/
    - assets/fair_core/