name: example
description: Fair example project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fair: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  # fair_compiler暂时通过path方式依赖，后期会发布到pub上
  fair_compiler:
    path: ../compiler

dependency_overrides:
  fair_version: 2.5.0

flutter:

  uses-material-design: true
