name: fair_annotation
description: Annotation package for Flutter Fair, work with fair compiler.
version: 0.2.0
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
